version: '3'

services:
  database_prod:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: papi
    volumes:
    - db-volume:/var/lib/postgresql/data

  api_prod:
    image: henres3605/praticando-api
    environment:
      DB_HOST: database_prod
    ports:
      - "9292:9292"
volumes:
  db-volume: