DELETE FROM ALUNO_CURSOS;
DELETE FROM CURSO;
DELETE FROM ALUNO;

ALTER TABLE CURSO ALTER COLUMN id RESTART WITH 1;
ALTER TABLE ALUNO ALTER COLUMN id RESTART WITH 1;

INSERT INTO CURSO(nome, nota, finalizado) VALUES('Python', 8, 1);
INSERT INTO CURSO(nome, nota, finalizado) VALUES('Java', 2, 1);
INSERT INTO ALUNO (NOME) VALUES ('Alex Albon');
INSERT INTO ALUNO_CURSOS  (ALUNO_ID , CURSOS_ID ) VALUES (1, 1);